name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    env:
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Env Vars
        run: echo "$COHERE_API_KEY" > backend/.env
      - name: Build the Docker image
        run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/cosona:latest backend/
      - name: Push Docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/cosona:latest
