name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build backend/ --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/cosona:latest
      - name: Push Docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/cosona:latest
